### ISSUE TITLE
Erreur Safe Portals

### ISSUE THREAD

**Issue by YoLaw** [AmauryCarrade/SafePortals#1]
Bonjour (Re)!
Suite à votre demande je pubblie ici les erreurs que la console m'a affiché au moment où j'ai passé le portail.

```
[18:29:02] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to SafePortals v1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.PlayerList.changeDimension(PlayerList.java:666) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.EntityPlayer.c(EntityPlayer.java:536) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.Entity.K(Entity.java:279) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:169) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:246) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1447) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:173) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:285) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:381) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:8) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
    at eu.carrade.amaury.SafePortals.SafePortalsUtils.isInsideBorder(SafePortalsUtils.java:26) ~[?:?]
    at eu.carrade.amaury.SafePortals.PortalsListener.onPlayerPortal(PortalsListener.java:32) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
    ... 23 more
```

Merci !

**Comment by AmauryCarrade** [comment]
Je vais regarder ça ce soir, merci.

**Comment by YoLaw** [comment]
Merci à vous

**Comment by AmauryCarrade** [comment]
Ça devrait être bon. [Disponible ici](http://jenkins.carrade.eu/job/SafePortals/) comme avant (compilation automatique). Signalez si le problème se reproduit (ou même si tout autre problème se produit) :) .

La version minimale a été changée, au passage : Bukkit 1.8.3 (mais personne ne devrait utiliser une version de CraftBukkit ou Spigot inférieure à la 1.8.7 de toute façon, les versions précédentes contenant des failles de sécurité majeures).

**Comment by YoLaw** [comment]
Super merci! :)
Nota Bene: Je connais pas mal de monde qui utilisent encore des versions Bukkit/Spigot 1.8.1...

**Comment by AmauryCarrade** [comment]
C'est une bien mauvaise idée... Mais libre à eux, c'est leur problème après tout.

**Comment by YoLaw** [comment]
Je suis bien d'accord avec ça! D'ailleurs je ne vois pas quelles sont les failles de sécurité...

**Comment by AmauryCarrade** [comment]
La plus grosse, c'est [celle-ci](http://blog.ammaraskar.com/minecraft-vulnerability-advisory/). [Mais il y en a d'autres](https://mojang.com/2015/06/minecraft-1-8-7-security-release/).

**Comment by YoLaw** [comment]
En effet.. Je savais pas que ce genre de choses était possible avant...
